name: "Issue Template"  # 템플릿 이름
description: "새로운 이슈를 생성하는 템플릿입니다. 아래 필드들을 입력해주세요."
labels: [feat]  # 기본 라벨을 필요에 따라 설정
body:
  - type: input
    id: ticketNum
    attributes:
      label: "Ticket Number"
      description: "이슈를 추적하는 티켓 번호를 입력하세요."
      placeholder: "예: OSP-123"
    validations:
      required: true

  - type: input
    id: branchName
    attributes:
      label: "Branch Name"
      description: "해당 이슈에서 작업할 브렌치 명을 영문으로 작성해주세요."
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: "Issue Description"
      description: "이슈에 대한 상세 설명을 작성하세요."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "Checklist"
      description: "이슈와 관련된 확인 항목들을 체크하세요."
      value: |
        - [ ] Task1
        - [ ] Task1
    validations:
      required: true
      
  - type: textarea
    id: notes
    attributes:
      label: "비고 (추가 설명)"
      description: "이슈와 관련된 추가 설명이나 참고 사항을 입력하세요."
